name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install foillib
        run: pip install .
          
      - name: Run tests
        run: python -m unittest tests/test_naca.py
        
      - name: Submit to codecov
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        run: |
          pip install coverage
          coverage run -m unittest tests/*.py 
          bash <(curl -s https://codecov.io/bash)
